version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
#    image: PousadaIstoE:0.0.1-SNAPSHOT
    container_name: PousadaIstoE
    restart: always
    volumes:
      - /home:/home
    ports:
      - 8081:8081
    environment:
#      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
#      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
#      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
#      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      ISTOE_DB_HOST: ${ISTOE_DB_HOST}
      ISTOE_DB_PORT: ${ISTOE_DB_PORT}
      ISTOE_USER_DB: ${ISTOE_USER_DB}
      ISTOE_PASS_DB: ${ISTOE_PASS_DB}


  db:
    restart: always
    image: postgres:14
    container_name: pgsql15
    hostname: pgsql14
    working_dir: /var/lib/postgresql/data
    ports:
      - "5434:5434"
    volumes:
        - /home/sam/pastaDocker/data:/var/lib/postgresql/data
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
        PGDATA: "/var/lib/postgresql/data/pgdata"


networks:
  default:
    external:
      name: microservices

